{
 "title": "Hadoop NN Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"hadoop-nn\"}, instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "hadoop-namenode" },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "数据源",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "集群信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存使用率",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(jvm_memory_pool_bytes_used{instance=~\"$instance\"}) by (instance) / (sum(jvm_memory_pool_bytes_max{instance=~\"$instance\"}) by (instance)))* 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])) by (instance) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NN节点",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"hadoop-nn\"}"
      },
      {
       "expr": "sum(Hadoop_NameNode_FilesTotal{job=\"hadoop-nn\"}) by (instance)"
      },
      {
       "expr": "sum(Hadoop_NameNode_CapacityUsed{job=\"$namespace\"}) by (instance)"
      },
      {
       "expr": "sum(Hadoop_NameNode_CapacityRemaining{job=\"$namespace\"}) by (instance)"
      },
      {
       "expr": "sum(Hadoop_NameNode_CapacityTotal{job=\"$namespace\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Hdfs平均写入时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "Hadoop_DataNode_WriteBlockOpAvgTime"
      }
     ]
    },
    {
     "title": "块总数\t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "Hadoop_NameNode_BlocksTotal{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}"
      }
     ]
    },
    {
     "title": "丢失块总数\t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "Hadoop_NameNode_MissingBlocks{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}\t"
      }
     ]
    },
    {
     "title": "损坏块总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "Hadoop_NameNode_CorruptBlocks{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}\t"
      }
     ]
    },
    {
     "title": "副本数不够的块数量\t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "Hadoop_NameNode_UnderReplicatedBlocks{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}\t"
      }
     ]
    },
    {
     "title": "datanode状态",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "Hadoop_NameNode_NumLiveDataNodes{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}",
       "legendFormat": "datanode存活数量"
      },
      {
       "expr": "Hadoop_NameNode_NumStaleDataNodes{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystemState\"}",
       "legendFormat": "datanode没有心跳数量"
      },
      {
       "expr": "Hadoop_NameNode_NumStaleDataNodes{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystemState\"}",
       "legendFormat": "datanode宕机数量"
      }
     ]
    },
    {
     "title": "磁盘容量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "Hadoop_NameNode_CapacityTotal{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
       "legendFormat": "磁盘总容量"
      },
      {
       "expr": "Hadoop_NameNode_CapacityUsed{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
       "legendFormat": "dfs使用量"
      },
      {
       "expr": "Hadoop_NameNode_CapacityUsed{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
       "legendFormat": "dfs剩余量"
      },
      {
       "expr": "Hadoop_NameNode_CapacityUsedNonDFS{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
       "legendFormat": "非dfs使用量"
      }
     ]
    },
    {
     "title": "datanode心跳",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "Hadoop_DataNode_HeartbeatsAvgTime"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Hadoop_NameNode_GcCount[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC时间",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Hadoop_NameNode_GcTimeMillis[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "年轻代GC累计次数",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{gc=\"ParNew\", instance=\"test-hadoop001:9222\", job=\"hadoop-nn\"}",
       "legendFormat": "test-hadoop001"
      },
      {
       "expr": "jvm_gc_collection_seconds_count{gc=\"ParNew\", instance=\"test-hadoop004:9222\", job=\"hadoop-nn\"}",
       "legendFormat": "test-hadoop004"
      }
     ]
    },
    {
     "title": "老年代GC累计次数",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{gc=\"ConcurrentMarkSweep\", instance=\"test-hadoop001:9222\", job=\"hadoop-nn\"}"
      },
      {
       "expr": "jvm_gc_collection_seconds_count{gc=\"ConcurrentMarkSweep\", instance=\"test-hadoop004:9222\", job=\"hadoop-nn\"}"
      }
     ]
    },
    {
     "title": "年轻代GC累计时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_sum{gc=\"ParNew\", instance=\"test-hadoop001:9222\", job=\"hadoop-nn\"}",
       "legendFormat": "test-hadoop001"
      },
      {
       "expr": "jvm_gc_collection_seconds_sum{gc=\"ParNew\", instance=\"test-hadoop004:9222\", job=\"hadoop-nn\"}",
       "legendFormat": "test-hadoop004"
      }
     ]
    },
    {
     "title": "老年代GC累计时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_sum{gc=\"ConcurrentMarkSweep\", instance=\"test-hadoop001:9222\", job=\"hadoop-nn\"}",
       "legendFormat": "test-hadoop001"
      },
      {
       "expr": "jvm_gc_collection_seconds_sum{gc=\"ConcurrentMarkSweep\", instance=\"test-hadoop004:9222\", job=\"hadoop-nn\"}",
       "legendFormat": "test-hadoop004"
      }
     ]
    },
    {
     "title": "堆使用情况",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "Hadoop_NameNode_MemHeapUsedM", "legendFormat": "{{instance}} used" },
      { "expr": "Hadoop_NameNode_MemHeapMaxM", "legendFormat": "{{instance}} max" }
     ]
    }
   ]
  },
  { "title": "JournalNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "journalnode内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=\"test-hadoop002:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop002已使用堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=\"test-hadoop003:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop003已使用堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=\"test-hadoop004:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop004已使用堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", instance=\"test-hadoop002:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop002已使用非堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", instance=\"test-hadoop002:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop003已使用非堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", instance=\"test-hadoop002:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop004已使用非堆内存(M)"
    }
   ]
  },
  {
   "title": "最大堆内存",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"test-hadoop002:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop002最大堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"test-hadoop003:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop003最大堆内存(M)"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"test-hadoop004:9522\", job=\"hadoop-journalnode\"}/1024/1024",
     "legendFormat": "test-hadoop004最大堆内存(M)"
    }
   ]
  }
 ]
}