{
 "title": "Yarn NM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NM节点",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AvailableGB) by (instance)"
    },
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedContainers) by (instance)"
    },
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB) by (instance)"
    },
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedVCores) by (instance)"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "GC次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NodeManager_GcCount[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NodeManager_GcTimeMillis[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NodeManager_MemHeapUsedM",
     "legendFormat": "{{instance}} used"
    },
    { "expr": "Hadoop_NodeManager_MemHeapMaxM", "legendFormat": "{{instance}} max" }
   ]
  }
 ]
}