{
 "title": "Yarn RM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RM节点",
   "type": "table",
   "description": "yarn resourcemanager节点",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableMB) by (instance)",
     "legendFormat": "主机"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedContainers{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "Containers运行中"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_PendingContainers{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "Containers等待执行数"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_ReservedContainers{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "Containers预定的"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedVCores{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "运行中的VCores"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableVCores{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "可用的VCores"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_ReservedVCores{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "预定的VCores"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_PendingVCores{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "等待执行的VCores"
    }
   ]
  },
  { "title": "作业", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "预占内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_ReservedMB/1024"
    }
   ]
  },
  {
   "title": "预占CPU核数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_ReservedVCores"
    }
   ]
  },
  {
   "title": "分配内存数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "Hadoop_NodeManager_AllocatedGB" }
   ]
  },
  {
   "title": "分配CPU核心数\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AllocatedVCores\t"
    }
   ]
  },
  {
   "title": "Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "作业等待数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsPending{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "失败作业数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsFailed{q1!=\"\", user=\"\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "正在运行作业数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning{job=\"hadoop-resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"flink_job\"})",
     "legendFormat": "flink_job队列"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning{job=\"hadoop-resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"hive_job\"})",
     "legendFormat": "hive-job队列"
    }
   ]
  },
  {
   "title": "分配容器数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AllocatedContainers"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "GC次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_ResourceManager_GcCount[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_ResourceManager_GcTimeMillis[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_MemHeapUsedM",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "Hadoop_ResourceManager_MemHeapMaxM",
     "legendFormat": "{{instance}} max"
    }
   ]
  }
 ]
}