{
 "title": "Hadoop DN Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"hadoop-dn\"}, instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "hadoop-dn" },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "数据源",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DN节点",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$namespace\"}"
    },
    {
     "expr": "Hadoop_DataNode_DfsUsed{job=\"$namespace\", name=\"FSDatasetState\"}/1024/1024/1024"
    },
    {
     "expr": "Hadoop_DataNode_Capacity{job=\"$namespace\", name=\"FSDatasetState\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Hdfs平均写入时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "Hadoop_DataNode_WriteBlockOpAvgTime"
    }
   ]
  },
  { "title": "仪表盘", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_pool_bytes_used{instance=~\"$instance\"}) by (instance) / (sum(jvm_memory_pool_bytes_max{instance=~\"$instance\"}) by (instance)))* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HDFS空间使用率",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_DataNode_DfsUsed{instance=~\"$instance\", name=\"FSDatasetState\"})"
    },
    {
     "expr": "sum(Hadoop_DataNode_Capacity{instance=~\"$instance\", name=\"FSDatasetState\"}) - sum(Hadoop_DataNode_DfsUsed{instance=~\"$instance\", name=\"FSDatasetState\"})"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GC次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_DataNode_GcCount[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_DataNode_GcTimeMillis[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Hadoop_DataNode_MemHeapUsedM", "legendFormat": "{{instance}} used" },
    { "expr": "Hadoop_DataNode_MemHeapMaxM", "legendFormat": "{{instance}} max" }
   ]
  }
 ]
}