{
 "title": "Zookeeper Dashboard",
 "description": "Metrics was extracted from jmx-exporter that reads JMX data from JVM based applications and exposes it via HTTP in a simple text format that Prometheus understand and can scrape. This dashboard was built for Zookeeper 3.5 version deployment in Local Cluster. You can select metrics based on Job & instance. This dashboard gives cross cluster zookeeper nodes information. It provides Quorum Size, Number of Followers, Member Type information, Healthcheck, Zookeeper metrics and JVM metics.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"$namespace\"}, instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "zookeeper" },
   {
    "name": "application",
    "label": "Application Name",
    "query": {
     "query": "query_result(process_start_time_seconds{_namespace_=\"$namespace\"})"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(process_start_time_seconds{_namespace_=\"$namespace\", application=\"$application\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quorum Size",
   "type": "stat",
   "description": "Quorum formed by zk nodes",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "avg(org_apache_ZooKeeperService_ReplicatedServer_id1_QuorumSize{instance=\"test-hadoop001:9923\", job=\"zookeeper\"})",
     "funcByType": "dimension"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "description": "number of followers within the ensemble. You can deduce the number of servers from the MBeam Quorum Size.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "avg(org_apache_ZooKeeperService_ReplicatedServer_id1_QuorumSize{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}) -1 ",
     "funcByType": "dimension"
    }
   ]
  },
  {
   "title": "Member Type",
   "type": "timeseries",
   "description": "Leader otrFollowers",
   "gridPos": { "h": 5, "w": 16, "x": 6, "y": 1 },
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_AvgRequestLatency{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "funcByType": "dimension",
     "legendFormat": "test-hadoop001"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_AvgRequestLatency{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_AvgRequestLatency{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Avg Request Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "ticks" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_AvgRequestLatency{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop001",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.AvgRequestLatency, 4, 6)"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_AvgRequestLatency{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_AvgRequestLatency{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003"
    }
   ]
  },
  {
   "title": "Znodes count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_NodeCount{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop001",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_NodeCount{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_NodeCount{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_NumAliveConnections{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop001"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_NumAliveConnections{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_NumAliveConnections{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.NumAliveConnections, 4, 6)"
    }
   ]
  },
  {
   "title": "Pending session revalidations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_PendingRevalidationCount{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop001",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_PendingRevalidationCount{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_PendingRevalidationCount{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_WatchCount{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop001",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_WatchCount{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_WatchCount{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id1_WatchCount{instance=\"test-hadoop001:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop001",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id2_WatchCount{instance=\"test-hadoop002:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop002"
    },
    {
     "expr": "org_apache_ZooKeeperService_ReplicatedServer_id3_WatchCount{instance=\"test-hadoop003:9923\", job=\"zookeeper\"}",
     "legendFormat": "test-hadoop003"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"[[instance]]\", job=\"$namespace\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSScavenge.CollectionTime.upper), 4)"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{instance=~\"[[instance]]\", job=\"$namespace\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSMarkSweep.CollectionCount.upper), 4)"
    }
   ]
  },
  {
   "title": "Heap Used vs Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"[[instance]]\", job=\"$namespace\", area=\"heap\"}",
     "legendFormat": "{{instance}} used",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_used.upper, 4, 6)"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=~\"[[instance]]\", job=\"$namespace\", area=\"heap\"}",
     "legendFormat": "{{instance}} max",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_max.upper, 4, 6)"
    }
   ]
  }
 ]
}